dbu_conference:
    resource: "@DbuConferenceBundle/Resources/config/routing.yml"
    prefix:   /

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"
create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

_imagine:
    resource: .
    type:     imagine

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
cmf_tree:
    resource: .
    type: 'cmf_tree'
