home_redirect:
    pattern: /
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        route: /cms/simple
        statusCode: 301
        useReferrer: false

dbu_conference_subscribe:
    path: /{_locale}/subscribe
    defaults: { _controller: DbuConferenceBundle:Subscribe:subscribe }

login:
    path:   /{_locale}/login
    defaults:  { _controller: DbuConferenceBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path:   /{_locale}/logout
